apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: cartservice
        image: 183631308419.dkr.ecr.us-east-1.amazonaws.com/cartservice:2
        ports:
        - containerPort: 80

