apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: jenkins
spec:
  selector:
    app: cartservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP